import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";
//import { Posting } from '../types/Posting';

//TODO: If posting === null show 404 page else show job posting

const JobPage: NextPage = () => {
  let jobId = useRouter().query.id?.toString();
  if(!jobId) jobId = "-1";
  const posting = trpc.useQuery(["jobs.getPostingById", { id: jobId }]);

  return (
  <>
    <Head>
      <title>Junior.Dev - Entry Level Jobs</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="">
      <div>JOB PAGE ID: {jobId}</div>
    </main>
  </>
  );
};

export default JobPage;
