import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const handleJobs = () => {
    router.push("/jobs");
  }

  return (
    <>
      <Head>
        <title>Junior.Dev - Entry Level Jobs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center py-12 p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700 font-mono">
          <span className="text-purple-600">Junior</span>.Dev
        </h1>
        <section>
          <p className="text-center font-mono font-semibold text-gray-700">I am trying to...</p>
          <div className="flex flex-row gap-4 py-8">
            <button className="bg-purple-600 text-white text-xl font-mono py-3 px-3 rounded hover:bg-purple-500 hover:scale-105">Post a Job</button>
            <button
              className="bg-purple-600 text-white text-xl font-mono py-3 px-3 rounded hover:bg-purple-500 hover:scale-105"
              onClick={handleJobs}
            >
              Find a Job
            </button>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
