import type { NextPage } from "next";
import Head from "next/head";
import Search from "../components/Search";
import { trpc } from "../utils/trpc";

const Jobs: NextPage = () => {
  //const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Junior.Dev - Entry Level Jobs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <section>
            <Search />
        </section>
      </main>
    </>
  );
};

export default Jobs;
