import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const NewPosting: NextPage = () => {
  //const postings = trpc.useQuery(["jobs.getAll"]);

  return (
    <>
      <Head>
        <title>Junior.Dev - Entry Level Jobs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="bg-purple-200 w-screen h-screen">
        <section className="pt-12">
          <div className="bg-white mx-auto max-w-6xl rounded-lg p-8 text-center">
            <div className="text-2xl font-semibold">Create a Job Posting</div>
            <form>
              <div className="flex flex-col gap-2 pt-8">
                <label className="text-lg">Company Name</label>
                <input className="bg-gray-200 p-2 rounded-lg w-72 mx-auto" />
              </div>
            </form>
          </div>
        </section>
      </main>
    </>
  );
};

export default NewPosting;
